//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_don_hang
    {
        public int chi_tiet_don_hang_id { get; set; }
        public Nullable<int> don_hang_id { get; set; }
        public int so_luong { get; set; }
        public decimal gia { get; set; }
    
        public virtual don_hang don_hang { get; set; }
    }
}
