//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class don_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public don_hang()
        {
            this.chi_tiet_don_hang = new HashSet<chi_tiet_don_hang>();
            this.thanh_toan = new HashSet<thanh_toan>();
        }
    
        public int don_hang_id { get; set; }
        public Nullable<int> nguoi_dung_id { get; set; }
        public Nullable<System.DateTime> ngay_dat { get; set; }
        public decimal tong_tien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thanh_toan> thanh_toan { get; set; }
    }
}
