//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prj2_2210900044_nhmEntities : DbContext
    {
        public prj2_2210900044_nhmEntities()
            : base("name=prj2_2210900044_nhmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual DbSet<danh_muc_san_pham> danh_muc_san_pham { get; set; }
        public virtual DbSet<don_hang> don_hang { get; set; }
        public virtual DbSet<nguoi_dung> nguoi_dung { get; set; }
        public virtual DbSet<san_pham> san_pham { get; set; }
        public virtual DbSet<thanh_toan> thanh_toan { get; set; }
    }
}
