//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoi_dung()
        {
            this.don_hang = new HashSet<don_hang>();
        }
    
        public int nguoi_dung_id { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public string email { get; set; }
        public string ho_ten { get; set; }
        public string dia_chi { get; set; }
        public string so_dien_thoai { get; set; }
        public Nullable<System.DateTime> ngay_dang_ky { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don_hang> don_hang { get; set; }
    }
}
