//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class san_pham
    {
        public int san_pham_id { get; set; }
        public string ten_san_pham { get; set; }
        public decimal gia { get; set; }
        public string mo_ta { get; set; }
        public Nullable<int> danh_muc_id { get; set; }
    
        public virtual danh_muc_san_pham danh_muc_san_pham { get; set; }
    }
}
