//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanh_toan
    {
        public int thanh_toan_id { get; set; }
        public Nullable<int> don_hang_id { get; set; }
        public string phuong_thuc { get; set; }
        public string trang_thai { get; set; }
        public Nullable<decimal> so_tien { get; set; }
        public Nullable<System.DateTime> ngay_thanh_toan { get; set; }
    
        public virtual don_hang don_hang { get; set; }
    }
}
